# Root options

[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    # 确保这个建议是正确的，如果不是，可以移除
    #"RUSTSEC-2023-0071",
]

[licenses]
allow = [
# "Panoptix",
  "Apache-2.0",
  "BSL-1.0",
  "BSD-2-Clause",
  "BSD-2-Clause-FreeBSD",
  "BSD-3-Clause",
  "CC0-1.0", # used only by constant_time_eq
  "ISC",
# "LLVM-exception",
  "MIT",
  "MPL-2.0",
  "Unlicense",
  "Unicode-DFS-2016",
  "Zlib",
]
#  "CC0-1.0",
#  "0BSD",
#  "zlib-acknowledgement",
confidence-threshold = 0.8
exceptions = [
  # 确保这些例外是正确的，如果不是，可以移除或修改
  #{ allow = ["Zlib"], crate = "adler32" },
  { allow = ["OpenSSL"], crate = "ring" },
  { allow = ["0BSD"], crate = "mock_instant" },
  { allow = ["zlib-acknowledgement"], crate = "fastdivide" },
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = [
  { crate = "base64" },
  { crate = "bitflags" },
  { crate = "heck" },
  { crate = "rustls-pemfile" },
  { crate = "syn" },
  { crate = "windows-sys" },
  { crate = "windows-targets" },
  { name = "ring", licenses = [], reason = "" },
  { name = "webpki", licenses = [], reason = "" },
]
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
